version: "3.7"

services:
  database: 
    image: postgres
    container_name: vaivoa-challenge
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=vaivoa
      - POSTGRES_PASSWORD=vaivoa
      - POSTGRES_DB=vaivoa-challenge
    volumes: 
      - pgdata:/data/postgres

volumes:
  pgdata: 
    driver: local