// <auto-generated />
using Card;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace vaivoa_challenge.Migrations {
  [DbContext(typeof(CardContext))]
  [Migration("20210527114840_InitialCreate")]
  partial class InitialCreate {
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
      #pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("Relational:MaxIdentifierLength", 63)
        .HasAnnotation("ProductVersion", "5.0.6")
        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

      modelBuilder.Entity("Card.Card", b => {
        b.Property<string>("id")
          .HasColumnType("text");
        
        b.Property<string>("card_number")
          .HasColumnType("text");
          
        b.Property<string>("email")
          .HasColumnType("text");

        b.HasKey("id");

        b.ToTable("Cards");
      });
      
      #pragma warning restore 612, 618
    }
  }
}
